### ISSUE TITLE
Issues with recent build on Windows

### ISSUE THREAD

**Issue by B-Keeper** [LuisAntonRebollo/Torque3D#31] opened 2014-02-05 18:32 UTC
Hi Luis,

First of all, thank you very much for your work on the OpenGL renderer!

Though I'm aware that it's under heavy development, I decided to give it a try. I've downloaded a snapshot of the dev_linux_opengl branch, then made a few modifications (taken from here: https://github.com/GarageGames/Torque3D/pull/558) to get it to build under VS2013 Express.

Compiling went fine, the default D3D renderer works as expected, but with the GL renderer, everything (both 2D and 3D) looks like this: http://s9.postimg.org/mz75fwe2n/Untitled.png

(This is windowed mode, 800x600, I've just cropped the window border, but it looks the same in all resolutions, both fullscreen and windowed.)

Also note that even if the screen is mirrored like this, the GUI layout appears to remain correct. If I move the mouse pointer over the 'Play' button at the bottom of the screen, the 'Exit' button will be highlighted.

And finally, I can't even really play the game. For some reason, loading is extremely slow (even if I've built the cached .dts models), then after I get to the game screen, everything in the 3D scene is completely black, then if I try to fire a weapon, the game crashes.

My CPU is an AMD Phenom II, and my GPU is a Radeon HD 4200. The OS is Windows 7 64-bit, and I have all the latest drivers.

Finally, here's a console log  from a session where I try to load the 'Empty Room' level, then try to fire the weapon, and the game crashes: http://pastebin.com/cB0K57E3

If it's a known issue, then I'm sorry for this report. I just thought it would be a good idea to let you know about this.

**Comment by LuisAntonRebollo** [comment] 2014-02-06 13:12
Thanks for all information you bring, I will be very useful to solve the problem.

**Comment by LuisAntonRebollo** [comment] 2014-02-08 12:18
After testing on the old computer from a friend( Windows XP 32bit, ATI HD5450):
- On DX9 Everything works correctly.
- I was able to reproduce this error **error (# 230) Overloaded functions must have the same parameter qualifiers in**, but was solved by updating the drivers for the graphic card.
- I could not reproduce the render upside down problem.
- The strangest is that it takes 10 minutes to load 'Full template mission' when using OpenGL. With DX9 load in less than 1 min.

I'll try to access the computer longer to install Visual Studio and investigate the issue of mission loading time.

**Comment by B-Keeper** [comment] 2014-02-08 12:58
Hi Luis,

Thanks for your response.

I might be wrong on this, but after taking a better look at the console log, I believe the slow loading time could be caused by the engine trying to compile the shaders, and since it fails, it tries to rebuild them every time a mission is loaded.

As for the upside-down problem, then it seems that only the Mobility line of Radeon GPUs are affected.

**Comment by rextimmy** [comment] 2014-02-13 22:43
Hi B-Keeper, sorry i didn't notice you opened this issue.

Could you confirm exactly the catalyst version you are using because this part from your log "Version : '3.3.11672 Compatibility Profile Context'" 3.3.11672 i believe equals catalyst 13.1?

**Comment by B-Keeper** [comment] 2014-02-13 23:06
Here's a detailed version report:

Catalyst Version: 13.9
2D Driver Version: 8.01.01.1248
Direct3D Version: 7.14.10.0911
OpenGL Version: 6.14.10.11672

**Comment by rextimmy** [comment] 2014-02-13 23:25
Ok thanks, i see what AMD are doing here. The legacy catalyst drivers are just shipping older GL/D3D drivers that have not been updated in a long time. That card is a D3D10 card too isn't it, no D3D11?

**Comment by B-Keeper** [comment] 2014-02-13 23:59
Definitely not a DX11-capable card. It can render some simple DX10 apps, therefore it can be considered a DX10 card, but I doubt it would be able to produce acceptable framerates with more complex scenes.

**Comment by rextimmy** [comment] 2014-02-14 00:21
I'll try and find some drivers for my card that match your OpenGL driver version you are using.

**Comment by rextimmy** [comment] 2014-02-14 02:46
I have figured out what is happening with these drivers now, i'll try and explain the best i can:

When the DX11 capable cards came out AMD have fixed up their OpenGL drivers dramatically (whether they did a re-write or just fixed bugs, it doesn't matter). So basically what we are left with is two sets of drivers

A) OpenGL 3.2 max support (buggy as hell)
B) OpenGL 4.x support.(pretty decent)

Driver set A: This is legacy stuff like your 4200 series and also anyone using Catalyst version less than 13. This driver set will never be updated or fixed.

Driver set B: No legacy support at all, only for DX11 cards and seemed to be introduced in Catalyst 13.x 

If you have a legacy card it doesn't matter version Catalyst you are using, you are stuck with driver set A.

Without even checking AMD driver version if OpenGL reports version 3.2 with AMD you will see your problem above because it's using Driver A. If OpenGL reports 4.x than all is good because we are using Driver B

Now that i can reproduce your problem i can implement a fix :-)

**Comment by LuisAntonRebollo** [comment] 2014-02-14 11:37
Thanks for your research.

It seems that we will not be able deprecated DX9, the sopport of OpenGL on old cards will be very bad.

**Comment by rextimmy** [comment] 2014-02-14 11:58
To be perfectly honest i think the DX9 device is a really good fall back device for the simple reason that OpenGL support for 2.1 is poor and that is been nice ;-), good quality D3D9 drivers are avaible from every manufacturer. From my experience if a card doesn't support GL 3.2 than it's not worth even targeting that device simply because the OpenGL drivers available for that card is crap and just not good enough. I can't help but feel a OpenGL 3.2 device is maybe a better option.

**Comment by B-Keeper** [comment] 2014-02-14 20:19
Thanks for your work, and if you need to test something on this card, I'll try to do it as soon as possible.

Now a bit off-topic, but regarding the 'good quality D3D9 drivers', I can confidently say this is not true, or at least not with this card. In all the games/engines I've been trying out that had both GL and D3D render systems, the GL renderer always performed better.

Torque3D is no exception, with the D3D renderer, it lags and glitches during most situations.

**Comment by rextimmy** [comment] 2014-02-15 00:52
I'll set up a new branch for this, i'll update this thread with details once i have something for you to test.

**Comment by rextimmy** [comment] 2014-02-15 05:39
Hey for now, this is a mini fix. There is more to fix up but you should be able to at least see the menu's and everything the right way up ;-)

Open up shaders\common\gl\torque.glsl in you game folder

There is 3 overloaded function called determinant starting at line 242, rename these three to something like determinantGLSL or whatever you choose for now. Now same file go to line 307 and update the determinant function there to whatever you called it above. Run your app again and hopefully it's better. This is not the full solution yet but it's enough to get the app at least working for now.

I can only guess the buggy glsl compiler (that is fixed in later driver versions) gets very confused because determinant function is from GLSL 1.5 and i think amd accidentally included it when compiling to version 1.2 of GLSL BUT than if you try to use the function the glsl compiler spits a warning saying this a GLSL 1.5 function lol. They stuffed that up good and proper

**Comment by B-Keeper** [comment] 2014-02-15 10:49
As usual, it worked, and not only fixed the upside-down issue, but now 3D scenes are rendered correctly, and I can play the game. Ther are some lighting/shadowing issues (I guess those shaders need to be reworked, too), but at least the game works! (And the game already runs much smoother and is more responsive in GL mode than with the default renderer.)

Thank you!

**Comment by rextimmy** [comment] 2014-02-16 01:09
Glad it worked, i have to finish off this texture manager problem first and than i'll get back to this one ok, it's just the other issue is affecting more people.

**Comment by rextimmy** [comment] 2014-02-16 06:14
Just out of curiosity B-Keeper, try the latest commit that luis just pushed up and see if that fixes your problem with out the above work around.

**Comment by B-Keeper** [comment] 2014-02-16 14:01
I can't do it right now, but I'll get and build the latest commit tonight and see how it goes.

**Comment by rextimmy** [comment] 2014-02-16 14:06
No hurry at all, whenever you have free time ;-)

**Comment by B-Keeper** [comment] 2014-02-16 16:28
Okay, so I built 320284d75b954dc89306575ecf29d6d4669cf458, without any of your fixes posted in this thread.

The upside-down issue has been fixed, but loading is still slow, and the 3D scene is still completely black (and the game still crashes when I try to fire a weapon).

**Comment by LuisAntonRebollo** [comment] 2014-02-16 23:24
@B-Keeper, that commit has no relation with rextimmy work. 

it's just a coincidence that the upside-down render is fixed.

**Comment by rextimmy** [comment] 2014-02-16 23:30
Yeah i only mentioned it because i noticed you did away with a few of the shaders that where causing compiling problems on these cards ;-)

**Comment by rextimmy** [comment] 2014-02-17 10:02
Anyway B-Keeper i'm going to go back to working on my Physx3 plugin for torque, Luis seems pretty snowed under with stuff to do for now, so i don't want to make his work even harder by issuing pull request after pull request. I'll come back in a few weeks or a month and see how things are going than for luis.

If you are interested in checking out the physx3 stuff than take a look here https://github.com/rextimmy/Torque3D/tree/physx3

**Comment by B-Keeper** [comment] 2014-02-17 10:54
Good luck with your project. You've already made much progress for us ATI card owners, so thank you very much!

**Comment by LuisAntonRebollo** [comment] 2014-02-17 12:16
@rextimmy thx for your work. 

I'll check slowly  all your work and I will add it :smile:

**Comment by rextimmy** [comment] 2014-02-17 12:35
That's ok Luis, keep up the good work on the GL/Linux/OSX port. You have my email now, so feel free to email me after things quieten down a little. I know how hard it can be when you are on a roll with something and than someone else joins in, it can actually slow you down a fair bit as you have to check there work, merge it with your own etc etc.

**Closed as completed** 2014-03-12 00:29 UTC
Labels: bug, opengl
